### ISSUE TITLE
Make fellowship endpoints public

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/sef-core#51]
**Is your feature request related to a problem? Please describe.**
We need `GET certificate by id` endpoint public because we need to display the content in our main website.

**Describe the solution you'd like**
- Divide the current controller into two categories as `fellowship` and `fellowship/admin`
- Create a new package for fellowship and add all the necessary files 
- Grant public access to `/fellowship` endpoints and make `/fellowship/admin` endpoints authorized

**Additional context**
Take a look at the `academix` package to get an idea

**Comment by YohanAvishke** [comment]
Fixed in https://github.com/sef-global/sef-core/pull/47
