### ISSUE TITLE
Add "New sub category" & "New item" buttons in the relevant pages.

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/sef-core#86]
**Is your feature request related to a problem?**
Add category button is duplicated twice in the header and categories page.

**Describe the solution you'd like**
Remove add-category button from the categories page.

**Screenshot**
![Screenshot from 2020-07-20 13-17-46](https://user-images.githubusercontent.com/60275681/87912729-8347b100-ca8b-11ea-890c-18012aa706b5.png)

**Comment by anjula-sack** [comment]
But there's an already button called "Add". We don’t need another button to do this. I think you should remove that Add New Category button and try to find a way to improve that add button. @Gimhan-minion

**Comment by anjula-sack** [comment]
@Gimhan-minion Change the issue title too
